### ISSUE TITLE
Bug with Localizoom non-lin

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/QuickNII#2]
When working with non-Lin. http://www.nesys.uio.no/NonLinTest/filmstripzoom.html?atlas=300000&series=4806&preview=ABAMousev2Preview.png.
first section was ok but second section won't save the transformed coordinates if the web tab is not closed.

**Comment by Tevemadar** [comment]
This issue is not related to QuickNII.
Done. "Save", export to "Excel" and "MeshView" buttons open new tabs.

**Comment by Tevemadar** [comment]
This one is possible to do, but requires substantial work. At the moment there is no zooming in VisuAlign (or QuickNII), and thus adding it is completely new, regardless of resolution.
