### ISSUE TITLE
python binding/script

### ISSUE THREAD

**Issue by orena1** [Neural-Systems-at-UIO/QuickNII#25]
Hi,
Assuming I have a transformation of an image. 
```
='ox=78.96794382940516&amp;oy=68.4588833448534&amp;oz=301.3318563811956&amp;ux=323.0130983390201&amp;uy=16.995857320965797&amp;uz=-36.838526340134706&amp;vx=-32.667850337151556&amp;vy=32.55494813946791&amp;vz=-270.67826047541917'
```
And I want to apply the same transformation to many different images, is there any python code available to do it? 
Thanks

**Comment by Tevemadar** [comment]
Those many different images, are they some kind of channels/modalities of a single tissue sample?

**Comment by Tevemadar** [comment]
Without further details, I can only provide some generic links:
* https://github.com/Tevemadar/QuickNII-extras has some small pieces of code, amongst them is a Python implementation of the propagation algorithm - that may or may not be what this question is about
* https://www.nitrc.org/plugins/mwiki/index.php/quicknii:MainPage has some description of the internals of QuickNII, with some code snippets included here and there, usually in Python.
