### ISSUE TITLE
Export slices from command line

### ISSUE THREAD

**Issue by paulbrodersen** [Neural-Systems-at-UIO/QuickNII#26]
Hi, thanks for creating QuickNII and making it available for the wider community. 

I am using QuickNII together with DeepSlice. DeepSlice seems to be working well for my data, so usually all I have to do is load the DeepSlice XML file into QuickNII, and hit "Export Slices". Since I have a large number of brains to process, and the next step in my pipeline involves a manual validation step anyway (that would also catch any registration issues), I am tempted to automate this process. **Does QuickNII support exporting slices from command line given a proper XML file containing the registration results, or could this feature be reasonably easy implemented?** I am imagining something along the lines of

```shell
java -cp Serv Serv ABA_Mouse_CCFv3_2017_25um.cutlas --xml /path/to/deepslice_results.xml --export
```

(I am using the linux patch, which works great).

**Comment by Tevemadar** [comment]
You can try NIISlicer from https://github.com/Tevemadar/QuickNII-extras/tree/master/Java
As it requires a NIfTI volume to slice, it may be worth adding that [VisuAlign](https://www.nitrc.org/projects/visualign/) contains such volumes.

**Comment by paulbrodersen** [comment]
Thanks for the quick reply. I will try that out.
