### ISSUE TITLE
Assigning ABA voxel coordinates to image pixels 

### ISSUE THREAD

**Issue by paulbrodersen** [Neural-Systems-at-UIO/QuickNII#27]
Hi, me again.

It's probably worth mentioning on the documentation page ["Assigning voxel coordinates to image pixels"](https://www.nitrc.org/plugins/mwiki/index.php?title=quicknii:Image_coordinates) that if one wants to assign ABA voxel coordinates, one still needs to switch and flip the axes after the matrix multiplication:

```
xv_ABA, yv_ABA, zv_ABA = 528 - yv, 320 - zv, xv
```

This is documented in some ways on [the coordinate system documentation page](https://www.nitrc.org/plugins/mwiki/index.php?title=quicknii:Coordinate_systems), but it still took me a few hours of banging my head against the wall until the penny finally dropped.

**Comment by Tevemadar** [comment]
Thanks, there's truth in your comment. Now the Image coordinate page ends with a short description about what was actually calculated there, and a link to the Allen CCF/WHS page.

**Comment by Majpuc** [comment]
Done
