### ISSUE TITLE
Bug 2 Nonlin

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/QuickNII#3]
When trying to load saved non-lin coordinates for a section, the new coordinates are not uploaded if the web tab is not closed.

**Comment by Tevemadar** [comment]
Is it different from https://github.com/Neural-Systems-at-UIO/QuickNII/issues/2 ?

**Comment by Majpuc** [comment]
Hi Gergely,
Maybe not. I just separated the issues because one was when try to upload previously saved coordinates and the other was simply going to process next slide.
Mvh, Maja

Sent from my iPad

On 18 Oct 2019, at 04:17, Gergely Csucs <notifications@github.com> wrote:

﻿

Is it different from #2<https://github.com/Neural-Systems-at-UIO/QuickNII/issues/2> ?

**Comment by Tevemadar** [comment]
Issue is not related to QuickNII, but solved as part of https://github.com/Neural-Systems-at-UIO/QuickNII/issues/2
