### ISSUE TITLE
Translate coordinates into slice's number

### ISSUE THREAD

**Issue by Noy987** [Neural-Systems-at-UIO/QuickNII#30]
Is there a way to translate the coordinates into the slice's number in QuickN11 ?

Thanks, appreciate it!

**Comment by Majpuc** [comment]
Hi Noy,

I am not sure I understand what you are asking. Could you explain what you are trying to do?

**Comment by Noy987** [comment]
After I adjust the brain slice in QuickN11, I export the JSON file load it to Nutil.
Nutil asks for the slice number (for example _s281) which I have to find manually by using the ABBA brain atlas. 
Wanted to know if QuickN11 could give me the slice number automatically by having the coordinates of the slice, shown in the screenshot at the top bar under the name "COR" on the right.

Thanks!

![quickN11](https://github.com/Neural-Systems-at-UIO/QuickNII/assets/154227249/a86f5b26-130f-4f6b-a94f-4c866a70383c)

**Comment by Majpuc** [comment]
Dear Noy, 
I understand the issue. QNII cannot give you the section number. Your files should already tbe named according to our naming convention _sXXX. Nutil Quantifier is looking for the section number in your file name. In Nutil quantifier, choose between the options  _sXXX or use a custom RegEx if you have an alternative file name. The  section number is corresponding to the antero-posterior position of the brain, usually starting with the apical end (olfactory bulb) and ending with the cerebellum. See instructions here: 
https://nutil.readthedocs.io/en/latest/QuantifierInput.html#file-naming-requirement.

I hope this helps,

Best, Maja

**Comment by Noy987** [comment]
Thanks so much!
Do you know of a program that can tell the section number automatically?

**Comment by Majpuc** [comment]
Dear Nøy,

If you are working with coronal mouse brain sections, you can try our automatic section registration tool DeepSlice
www. deepslice.org

Best, Maja

**Comment by Noy987** [comment]
Thanks Maja! 

I am working with DeepSlice, but unfortunately once I load my slices to DeepSlice, the output files that I download don't have the slice number in their files' name. 
The downloaded files are simply named "results" (shown in the screenshots).
Inside them, the "file name" is its original name saved on my computer, for example "slice1-dapi_resized" (shown in the screenshots). 
Is the slice number somewhere else in the files or the website?

![image](https://github.com/Neural-Systems-at-UIO/QuickNII/assets/154227249/6d0a585d-dff5-447e-8b2e-7e359a9eee75)
![file name](https://github.com/Neural-Systems-at-UIO/QuickNII/assets/154227249/0670cebe-b229-4107-a93d-655faaf2894c)
![file](https://github.com/Neural-Systems-at-UIO/QuickNII/assets/154227249/8e239cd9-8d02-4092-8769-63359ead79a3)

**Comment by Majpuc** [comment]
Dear Noy,

The slice number is the one you give to your images. Naming them 1,2,3,4 etc.. is ok.
From DeepSlice you will obtain a JSON file containing the coordinates of each 2D image in the atlas space. 
You can open this Json file in QuickNII and VisuAlign if you want to correct the alignment manually.
Further, when you are satisfied with the registration results, and have obtained segmentation files of your cells, you can use Nutil to obtain the number of objets/cells per atlas region or the area coverage (load) in each region. 
In Nutil quantifier, you will have to use "user defined" naming of your sections. More info here: https://nutil.readthedocs.io/en/latest/QuantifierInput.html

The name of you images will remain the name you gave to your files.

I hope this clarifies your issue.

Best, Maja

**Comment by Noy987** [comment]
Okay I understand, thank you very much!
