### ISSUE TITLE
Prepare QNII dev atlases for publication on Nitrc

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/QuickNII#4]
The mouse dev atlases will be published on Nitrc.

- Is the current package ready for that?  the launching of QNII seems to be different that for other atlases, i.e. launched from the bat file instead of the QNII icon. Do we need an adjustment here? Version number?

- We need to prepare all necessary documentation  and citations as well as a version number.

**Comment by ingvildeb** [comment]
**Concerns before publishing QNII dev atlases:** The templates should be brightened (the images are very dark, and how to increase brightness in QuickNII is not very intuitive for the user) and ideally we want to do something about two of the lower resolution of two of the dimensions. We also need to keep in mind that ~100 datasets have now been registered to the current versions, so we need a solution for automatic translation if we change the template.

**Comment by Majpuc** [comment]
We have decided not to publish these QNII versions yet. An alternative solution will be to share the correct Localizoom links from the EBRAINS dataset card.
